# Generated by Django 2.2.10 on 2020-03-07 10:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import learning_rebellion.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('slug', learning_rebellion.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='title', unique=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.FileField(blank=True, default=None, upload_to='images')),
                ('active', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('slug', learning_rebellion.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='title', unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.FileField(blank=True, default=None, upload_to='images')),
                ('active', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('url', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
