# Generated by Django 2.2.10 on 2020-02-25 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date tracked')),
                ('title', models.TextField()),
                ('slug', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('image', models.FileField(blank=True, default=None, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date tracked')),
                ('title', models.TextField()),
                ('slug', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('image', models.FileField(blank=True, default=None, upload_to='images')),
                ('file', models.FileField(blank=True, default=None, upload_to='podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date tracked')),
                ('ip', models.GenericIPAddressField()),
                ('agent', models.TextField(blank=True)),
                ('url', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
