# Generated by Django 2.2.10 on 2020-02-28 08:47

import ckeditor.fields
from django.db import migrations
import learning_rebellion.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_rebellion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='description',
        ),
        migrations.AddField(
            model_name='podcast',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='slug',
            field=learning_rebellion.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=learning_rebellion.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='title', unique=True),
        ),
    ]
