# Generated by Django 2.2.10 on 2020-02-28 08:10

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import learning_rebellion.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('slug', learning_rebellion.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='title', unique=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.FileField(blank=True, default=None, upload_to='images')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
